### ISSUE TITLE
Pulldown error on WSL2

### ISSUE THREAD

**Issue by remybonnav** [KosinskiLab/AlphaPulldown#131] opened 2023-05-14 09:53 UTC
I run into error when running the pulldown script.
I first had to instal ltensorflow 2.9.0 because it seems to not be installed properly by following the install of ALphaPulldown.

Then when I run the pulldown script
I get this error:
/.../wsl/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
I0514 11:47:36.752244 140225035278144 utils.py:175] checking if output_dir exists .../Alphapulldown/outGPU/
I0514 11:47:38.386346 140225035278144 run_multimer_jobs.py:178] done creating multimer
I0514 11:47:40.203128 140225035278144 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0514 11:47:40.490592 140225035278144 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I0514 11:47:40.491099 140225035278144 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0514 11:47:40.491259 140225035278144 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2023-05-14 11:47:41.855491: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 17178951680 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by henrywotton** [comment] 2023-05-14 09:58
Hi,

Thanks for your report. I think the issue is pretty straightforward. There is not enough memory on your GPU device. Maybe you could reserve a GPU card with larger RAM.

Cheers

**Comment by henrywotton** [comment] 2023-05-14 10:03
Sorry since this issue has nothing to do with the programme itself, I'll close it

**Closed by henrywotton** 2023-05-14 10:03 UTC
